# Generated by Django 6.0.5 on 2026-05-10 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa firmy')),
                ('description', models.TextField(verbose_name='Opis firmy')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo firmy')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email kontaktowy')),
                ('ust_id', models.CharField(max_length=50, verbose_name='USt-IdNr (NIP)')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Link do Facebooka')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Link do Instagrama')),
                ('treatwell_url', models.URLField(blank=True, null=True, verbose_name='Link do Treatwell')),
            ],
            options={
                'verbose_name': 'Dane firmy',
                'verbose_name_plural': 'Dane firmy',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('status', models.CharField(choices=[('new', 'Nowa'), ('in_progress', 'W trakcie realizacji'), ('closed', 'Zamknięta')], default='new', max_length=20, verbose_name='Status wiadomości')),
            ],
            options={
                'verbose_name': 'Formularz kontaktowy',
                'verbose_name_plural': 'Zgłoszenia z formularza kontaktowego',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł posta')),
                ('description', models.TextField(verbose_name='Opis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatments/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia posta')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posty',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nazwa usługi')),
                ('description', models.TextField(verbose_name='Opis zabiegu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena (€)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Usługa',
                'verbose_name_plural': 'Usługi',
            },
        ),
    ]
