# Generated by Django 5.2.13 on 2026-05-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='ust_id_information',
            field=models.TextField(blank=True, null=True, verbose_name='Informacje o USt-IdNr (NIP)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do WhatsApp'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Zdjęcie usługi'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='ust_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='USt-IdNr (NIP)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Opis'),
        ),
    ]
