# Generated by Django 6.0.4 on 2026-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contactmessage_is_read_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Formularz kontaktowy', 'verbose_name_plural': 'Zgłoszenia z formularza kontaktowego'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posty'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Usługa', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nowa'), ('in_progress', 'W trakcie realizacji'), ('closed', 'Zamknięta')], default='new', max_length=20, verbose_name='Status wiadomości'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(verbose_name='Opis firmy'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Facebooka'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Instagrama'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo firmy'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatments/', verbose_name='Zdjęcie'),
        ),
    ]
