# Generated by Django 5.2.13 on 2026-05-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Formularz kontaktowy', 'verbose_name_plural': 'Zgłoszenia z formularza kontaktowego'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category'], 'verbose_name': 'Usługa', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kraj'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='dispute_resolution_text',
            field=models.TextField(blank=True, help_text='Np. czy firma zgadza się na udział w mediacji przed organem konsumenckim', null=True, verbose_name='Deklaracja dot. rozstrzygania sporów'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='liability_contents',
            field=models.TextField(blank=True, null=True, verbose_name='Odpowiedzialność za treści (Haftung für Inhalte)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='liability_links',
            field=models.TextField(blank=True, null=True, verbose_name='Odpowiedzialność za linki (Haftung für Links)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_additional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dodatkowa nazwa firmy (np.Kosmetiksalon)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='odr_link',
            field=models.URLField(default='https://ec.europa.eu/consumers/odr/', verbose_name='Link do platformy ODR (wyszczególniony w prawie UE)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Imię właściciela'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='ust_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='USt-IdNr (NIP) - nieobowiązkowe do wpisania'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='ust_id_information',
            field=models.TextField(blank=True, null=True, verbose_name='Informacje o VAT / Zwolnieniu (np. § 19 UStG)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatments/', verbose_name='Zdjęcie kosmetyków'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nazwa kosmetyków których używamy'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Kategoria'),
        ),
    ]
