# Generated by Django 5.2.13 on 2026-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contactmessage_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='dispute_resolution_text',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='eu_streitschlichtung',
            field=models.TextField(blank=True, null=True, verbose_name='Rozstrzyganie sporów w UE (EU-Streitschlichtung)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='privacy_intro',
            field=models.TextField(blank=True, null=True, verbose_name='Polityka prywatności - Wstęp (Einleitung und Überblick)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='privacy_legal_grounds',
            field=models.TextField(blank=True, null=True, verbose_name='Polityka prywatności - Podstawy prawne (Rechtsgrundlagen)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='privacy_purposes',
            field=models.TextField(blank=True, null=True, verbose_name='Polityka prywatności - Cele (Zweck der Datenverarbeitung)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='privacy_third_parties',
            field=models.TextField(blank=True, null=True, verbose_name='Polityka prywatności - Przekazywanie danych (Datenübermittlung an Dritte)'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='privacy_accepted',
            field=models.BooleanField(default=False, verbose_name='Zaakceptowano politykę prywatności (Datenschutz)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo firmy - nie używane'),
        ),
    ]
