# Generated by Django 5.2.13 on 2026-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_companyinfo_dispute_resolution_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='ust_id_information',
            field=models.TextField(blank=True, null=True, verbose_name='Umsatzsteuer'),
        ),
    ]
