# Generated by Django 5.2.13 on 2026-05-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_companyinfo_ust_id_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='motto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motto firmy'),
        ),
    ]
