# Generated by Django 5.2.13 on 2026-06-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companyinfo_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cena do (€) - opcjonalnie'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Kategoria'),
            preserve_default=False,
        ),
    ]
