# Generated by Django 5.2.13 on 2026-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_price_to_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='city_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Miasto (drugi adres)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='country_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kraj (drugi adres)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Google Maps (Główny adres)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='map_url_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Google Maps (drugi adres)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_code_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod pocztowy (drugi adres)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='street_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ulica (drugi adres)'),
        ),
    ]
