# Generated by Django 5.2.13 on 2026-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_category_options_category_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Usługa', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność wyświetlania w kategorii - niższa liczba = pierwsze w kolejności'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność wyświetlania - im niższa, tym wyżej na stronie'),
        ),
    ]
