# Generated by Django 5.2.13 on 2026-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_service_options_service_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='privacy_cookies',
            field=models.TextField(blank=True, null=True, verbose_name='Polityka prywatności - Cookies'),
        ),
    ]
